# Generated by Django 4.1.3 on 2023-02-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookparking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='has_expired',
            field=models.BooleanField(default=False),
        ),
    ]
