# Generated by Django 4.1.3 on 2023-02-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookparking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='location',
        ),
        migrations.RemoveField(
            model_name='historicalbookings',
            name='location',
        ),
    ]
