# Generated by Django 4.1.3 on 2023-01-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookparking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveuser',
            name='is_customer',
            field=models.BooleanField(default=False, verbose_name='is_customer'),
        ),
        migrations.AlterField(
            model_name='reserveuser',
            name='is_employee',
            field=models.BooleanField(default=False, verbose_name='is_employee'),
        ),
    ]
