# Generated by Django 4.1.3 on 2023-02-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookparking', '0002_remove_bookings_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='checkin_datetime',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='checkout_datetime',
            new_name='check_out',
        ),
        migrations.RenameField(
            model_name='historicalbookings',
            old_name='checkin_datetime',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='historicalbookings',
            old_name='checkout_datetime',
            new_name='check_out',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='car_plate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='government_id',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbookings',
            name='car_plate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbookings',
            name='government_id',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
