# Generated by Django 4.1.3 on 2023-01-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookparking', '0002_alter_reserveuser_is_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaces',
            name='pricing_per_hour',
            field=models.IntegerField(default=0),
        ),
    ]
