# Generated by Django 4.1.3 on 2023-01-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookparking', '0003_spaces_pricing_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaces',
            name='location_image',
            field=models.ImageField(default='media/', upload_to='media/'),
            preserve_default=False,
        ),
    ]
