# Generated by Django 3.2.2 on 2023-03-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookparking', '0003_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_conflicting',
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout',
            field=models.DateTimeField(null=True),
        ),
    ]
