# Generated by Django 4.1.3 on 2023-02-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookparking', '0004_spaces_location_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='check_in_date',
            field=models.DateField(default='2023/02/14'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='check_out_date',
            field=models.DateField(default='2023/02/14'),
        ),
    ]
