# Generated by Django 4.1.3 on 2023-02-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookparking', '0004_rename_check_out_bookings_checkout_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookings',
            new_name='Booking',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='is_paid',
            new_name='is_conflicting',
        ),
        migrations.RemoveField(
            model_name='parkingspace',
            name='is_available',
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='HistoricalBookings',
        ),
    ]
