# Generated by Django 4.1.3 on 2023-02-14 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('bookparking', '0005_alter_bookings_check_in_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBookings',
            fields=[
                ('government_id', models.CharField(db_index=True, max_length=8)),
                ('car_plate', models.CharField(max_length=255)),
                ('check_in_date', models.DateField(default='2023/02/14')),
                ('check_out_date', models.DateField(default='2023/02/14')),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
                ('is_paid', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookparking.spaces')),
            ],
            options={
                'verbose_name': 'historical bookings',
                'verbose_name_plural': 'historical bookingss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
