# Generated by Django 4.1.3 on 2023-02-16 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookparking', '0005_rename_bookings_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookparking.location'),
        ),
    ]
