# Generated by Django 4.1.1 on 2023-03-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookparking', '0005_payout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payout',
            name='currency',
        ),
        migrations.AlterField(
            model_name='payout',
            name='payment_id',
            field=models.CharField(auto_created=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='transaction_id',
            field=models.CharField(auto_created=True, max_length=50, unique=True),
        ),
    ]
