# Generated by Django 4.1.1 on 2023-03-27 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookparking', '0007_delete_payout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(auto_created=True, unique=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('paid', 'paid'), ('not paid', 'not paid')], max_length=20)),
                ('payment_method', models.CharField(max_length=50)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookparking.parkingspace')),
            ],
        ),
    ]
