# Generated by Django 4.1.1 on 2023-03-30 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookparking', '0009_payout_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
